name: Streamlit Keep Alive

on:
  schedule:
    - cron: '0 * * * *' # Saatte bir çalışır
  workflow_dispatch:

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Send Persistent Request
        # continue-on-error: true sayesinde hata alsa bile GitHub kırmızı çarpı göstermez
        continue-on-error: true 
        run: |
          # --retry: Başarısız olursa 3 kez dene
          # --retry-delay: Denemeler arası 10 saniye bekle
          # -m 30: Maksimum 30 saniye bekle
          curl -I --retry 3 --retry-delay 10 -m 30 https://pediatricatopicdermatitis.streamlit.app/
