name: Streamlit Keep Alive

on:
  schedule:
    - cron: '0 * * * *' # Saatte bir çalışır
  workflow_dispatch:

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Persistent Ping
        run: |
          # Sadece başlık değil, tüm içeriği çekmeye çalışarak sunucuyu zorlar
          curl -L --retry 3 --retry-delay 5 https://pediatricatopicdermatitis.streamlit.app/
